feature:
  - any:
    - title: ['^feat(\(.+\))?:', '^feature(\(.+\))?:']
    - head-branch: ['^feat\/', '^feature\/']

bug:
  - any:
    - title: ['^fix(\(.+\))?:', '^bugfix(\(.+\))?:']
    - head-branch: ['^fix\/', '^bugfix\/']

refactor:
  - any:
    - title: ['^refactor(\(.+\))?:']
    - head-branch: ['^refactor\/']

style:
  - any:
    - title: ['^style(\(.+\))?:']
    - head-branch: ['^style\/']

chore:
  - any:
    - title: ['^chore(\(.+\))?:']
    - head-branch: ['^chore\/']

docs:
  - any:
    - title: ['^docs(\(.+\))?:']
    - head-branch: ['^docs\/']

test:
  - any:
    - title: ['^test(\(.+\))?:']
    - head-branch: ['^test\/']
